### PR TITLE
Upgrade to PHP 7.4.4

### PR DESCRIPTION
**Pull request by p1u3o**

### CODE REVIEW

**Comment by p1u3o** [comment]
I suspected aarch64 would break because upstream OpenLDAP updated their config files.

**Comment by Lctrs** [comment]
You would need to regenerate the patch with master `build/config.guess`. Support for aarch64 is only there AFAIK.

**Comment by p1u3o** [comment]
> You would need to regenerate the patch with master `build/config.guess`. Support for aarch64 is only there AFAIK.

I will try that.

**Comment by p1u3o** [comment]
We don't need to patch anything, the `build/config.guess` in the master tree matches 2.4.49 and contains the aarch64 definitions.

**Comment by Lctrs** [comment]
Cool.

LGTM then.

**Pull request merged**
