### PR TITLE
18.08 build

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by p1u3o** [comment]
I'm not so sure we need a 18.08 build.

VSCode, Atom and PHPStorm are all on the 19.08 runtime.

**Comment by Lctrs** [comment]
`com.visualstudio.code.oss` is still on `18.08`.

**Comment by p1u3o** [comment]
ugh.

**Comment by Lctrs** [comment]
Upgrading `com.visualstudio.code.oss` to `19.08` would be better indeed. But damn, what a complicated recipe. I've never been able to get their build script working locally.

**Comment by Lctrs** [comment]
I put this one on hold for now. Will try to update com.visualstudio.code.oss first.

**Comment by p1u3o** [comment]
Alright, if that fails I guess this is fine.

I'm just worried we're going to end up having to support 18.08, 19.08, 20.08, 21.08 and 22.08. When an LTS distro released in 2018 wouldn't even get PHP 7.4 it feels like backporting.

**Comment by Lctrs** [comment]
Here we go : https://github.com/flathub/com.visualstudio.code.oss/pull/51 :tada:

**Comment by p1u3o** [comment]
Awesome!

**Comment by Lctrs** [comment]
It has been merged. So closing this now.

**Comment by p1u3o** [comment]
Awesome stuff, congratulations on getting that fixed.

**Pull request closed without merging**
